name: chaldea_data
description: The data layer of clean `chaldea` project.
version: 0.1.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  chaldea_domain:
    git:
      url: https://github.com/karanokk/chaldea_domain

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
