name: test

on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: flutter-cache
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - name: Install Flutter
      if: steps.flutter-cache.outputs.cache-hit != 'true'
      uses: subosito/flutter-action@v1.3.2
    - name: Install app dependencies
      run: flutter pub get
    - name: Test app
      run: flutter test --coverage test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
